### ISSUE TITLE
Data in package and for benchmarking

### ISSUE THREAD

**Issue by jolars** [jolars/sgdnet#13]
I have currently opted to include rather large data sets in the package. The intent was originally to use these datasets both for examples and for benchmarking. However, the fact that they are large means that quite a few of the example run slowly. Perhaps this will be alleviated as the algorithm is optimized but it will likely always mean that we, for instance, cannot run automated valgrind builds on travis-ci. (They time out.)

More pertinently, perhaps, is that the data sets are supplemented by other data sets in the benchmarking because I thought it would be inappropriate to only benchmark for one data set for each family (and including several data sets for each response type seems like overkill). Therefore, the benchmarks have to be run "offline" and not at the time that the vignettes are built, which means we store the data (currently only in `benchmarks_binomial`) and then produce the vignettes off of these.

The issue is also the type of benchmarks that we would like to run. Currently, we are only fitting the models for single lambdas and varying over tolerance to return measures of loss and time. This is of course problematic because glmnet, which we want to compare against, is currently more efficient in fitting the full path (in the lasso case). However, since we are using different stopping criteria for the algorithms, just running the full path and not controlling for the objective loss appropriately risks biasing towards the algorithm that accepts looser fits (I am not sure which one that is at the moment.) I am not sure I exactly understand what glmnet

Anyway, the options as I see them are:

## Alternative 1: Large datasets in package, simple benchmarks
Keep the large datasets in the package, produce simpler benchmarks that can be run at the time the vignette is built.

### Pros:
* Don't have to remember to rerun the benchmarks every time the package is updated.
* Benchmarks possibly better reflect "real" use of the packages.
* Package is self-contained and vignettes reproducible without having to visit GitHub repo for source code. Don't have store internal data only used for vignettes.

## Alternative 2: Small datasets in package, extensive benchmarks (with large datasets)
Change to smaller datasets in the package for running examples and tests. In this case, I will probably create a separate R package for the datasets to be stored only on github.

### Pros
* Loss can be controlled and compared against.
* Pseudo-measure for visualizing convergence path
* Can run valgrind builds on travis-ci
* Smaller package footprint

**Comment by michaelweylandt** [comment]
Aren't we forced to do both elements of both Alternatives 1 and 2 by different CRAN checks? IIRC, CRAN already checks that all examples take <5s so we'll need small data sets, and checks vignette build time, so we'll be locked into having cached results somewhere.

**Comment by jolars** [comment]
Well it reports examples that take more than five seconds but doesn't throw a WARNING or even a NOTE:

See, for instance,

<https://travis-ci.org/jolars/sgdnet/jobs/404406711#L1173-L1176>

but I do think it is problematic with long-running examples anyway so I think that option is out. I'll get some new, smaller, data sets.

**Comment by michaelweylandt** [comment]
I don’t have any objection to simulated data in examples, (or benchmarks)
though Toby might.

**Comment by jolars** [comment]
The solution for now is to use smaller datasets in the examples and export them as part of the package whilst we'll use larger data sets for benchmarking.
