### ISSUE TITLE
First fit on automatic lambda path for ridge penalty

### ISSUE THREAD

**Issue by jolars** [jolars/sgdnet#19]
So, I just realized that glmnet does not fit the first lambda on the lambda path as advertised when `alpha = 0` (ridge penalty). Instead, it just fits the intercept-only model. However, this is only true when we are using the automatic path:

```r
x <- cbind(mtcars$hp, mtcars$drat)
y <- mtcars$hp
f1 <- glmnet::glmnet(x, y, alpha = 0, nlambda = 5)
f2 <- glmnet::glmnet(x, y, alpha = 0, lambda = f1$lambda)

coef(f1)
# 3 x 5 sparse Matrix of class "dgCMatrix"
# s0            s1           s2          s3         s4
# (Intercept)  1.466875e+02 147.266925785 150.70764862 131.7163971 36.5188046
# V1           1.010101e-36   0.009881444   0.08939354   0.4734925  0.8909357
# V2          -5.812650e-35  -0.564124780  -4.76373281 -15.1489993 -5.7055708

coef(f2)
# 3 x 5 sparse Matrix of class "dgCMatrix"
# s0            s1           s2          s3         s4
# (Intercept)  1.467475e+02 147.266925785 150.70764862 131.7163971 36.5188046
# V1           9.988002e-04   0.009881444   0.08939354   0.4734925  0.8909357
# V2          -5.743033e-02  -0.564124780  -4.76373281 -15.1489993 -5.7055708
```

Have a look at the first column.

As of c49cdab, we will do the same, that is, use the intercept-only model as the first fit on the automatic lambda path. This is obviously a little devious because the user probably does not except the runs to produce different output. It is, however, true to the idea of starting at a ridge penalty strength at lambda_max. It is also of course efficient.

## Alternatives
* We could diverge from glmnet and actually fit the model equal to the first lambda on the path. The downside is that results will no longer be equivalent for the ridge penalty and loss of efficiency.
* We could return the `Inf` as the first penalty on the path, which would probably be the most theoretically correct option. This also diverges from glmnet but only in regards to the lambda path that is returned to the user, not the actual fit. This also means that the first and second values aren't actually log-spaced anymore, but I'm not sure that matters much.

What do you think @michaelweylandt, @tdhock?

**Comment by michaelweylandt** [comment]
Bleh -- seriously!? That's just weird... (and possibly a bug worth reporting upstream)

I'm definitely ok with diverging from `glmnet` here - correctness is more important than consistency. 

My gut says to just get the right answer (i.e., your first alternative). I'm not clear what efficiency hit you're worried about. Can you elaborate? 

The `Inf` idea is nice (though would require a pretty clear note in the documentation since it's a bit nonstandard), but wouldn't it do weird things to our plots?

**Comment by jolars** [comment]
Hm, no actually it seems to have been documented.

> The actual sequence of lambda values used. When alpha=0, the largest lambda reported does not quite give the zero coefficients reported (lambda=inf would in principle). Instead, the largest lambda for alpha=0.001 is used, and the sequence of lambda values is derived from this.

Well, no maybe it doesn't mean that much overhead. Here is an example where 10 passes are required to fit the intercept

```r
library(sgdnet)
options(sgdnet.debug = TRUE)
fit <- sgdnet(heart$x, heart$y, family = "binomial", alpha = 0)
length(attr(fit, "diagnostics")$loss[[1]])
# [1] 10
sum(lengths(attr(fit, "diagnostics")$loss))
# [1] 604
```
10 from a total of 604 doesn't really seem like much of a big deal though.

It would mess up our plots but I believe that it could be easily fixed by simply capping the axes.

**Comment by michaelweylandt** [comment]
Documented, but still ... peculiar. 

If it's not a big efficiency loss, I'd just do it "right" and not be overly clever. (I would document that `glmnet` is doing something odd here to save you spurious bug reports)

**Comment by jolars** [comment]
Hm, yeah I think you're right. I reverted it back to the old behavior with 
2a70b25 and have made some notes regarding this in the documentation to sgdnet()
