### ISSUE TITLE
Separating sparse and dense implementations

### ISSUE THREAD

**Issue by jolars** [jolars/sgdnet#6]
I have begun to think that it might be wise to separate the sparse and dense implementations of the algorithm.

Here are the pros and cons that I can think of if we were to do this:

## Pros
* Avoid overhead from iterating across a vector for non-zero elements in the dense implementation for which it is pointless. This would also mean more compact code in `LaggedUpdate()` for the dense implementation.
* Allow use of `.colptr()`, `.unsafe_col()` and `.memptr()` for faster access to elements in the dense implementation.
* Avoid branching on sparse condition, for instance for in-place scaling and centering.

## Cons
* Code duplication, particularly in this stage where nothing is final.

Thoughts?

**Comment by jolars** [comment]
Nevermind, I changed my mind on this. If anything, it is more reasonable to provide separate overloaded functions for performance-critical parts.

**Comment by michaelweylandt** [comment]
Sounds fair -- agreed about overloads / templating where performance matters.
